# Generated by Django 2.1.2 on 2018-10-31 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20181031_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='dueDate',
            field=models.DateTimeField(blank=True),
        ),
    ]
